version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Choose your preferred Python version
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt  # If you have any dependencies

  pre_build:
    commands:
      - echo "Executing pre-build commands..."

  build:
    commands:
      - echo "Running tests..."
      - python test.py  # Execute your Flask app tests here

artifacts:
  files:
    - '**/*'  # Include all files in the build artifact

